console.log("shaurya");
var first="shaurya ";
var second="rathod";
console.log(first.concat(second));
var num1=2;
var num2=4;
console.log(num1+num2);
var mul1=5;
var mul2=2;
console.log(mul1*mul2);
var numarr=[1,2,3,4,5];
console.log(numarr);
var mulnames=["shaurya","shree","dipali","rahul"];
console.log(mulnames);
var number=["a","b","c",'d',"e"];
console.log(number);
console.log(mulnames[1]);
console.log(mulnames[3]);
console.log(number[2]);
console.log(true);
console.log(mulnames.length);
console.log(number.length);